name: Monthly Trend Analysis

on:
  schedule:
    - cron: '0 2 30 * *'  # 每月30日10:00（UTC时间+8）
  workflow_dispatch:

jobs:
  run-monthly:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run monthly_analyzer.py
        run: python monthly_analyzer.py
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_APP_PASS: ${{ secrets.SMTP_APP_PASS }}