name: Weekly Inventory Report

on:
  schedule:
    - cron: '0 2 * * 5'  # 每周五上午10点（UTC时间+8）
  workflow_dispatch:

jobs:
  run-weekly:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run weekly_reporter.py
        run: python weekly_reporter.py
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_APP_PASS: ${{ secrets.SMTP_APP_PASS }}
